stages:
    - build
    - test

before_script:
    - dos2unix `find . -type f \( -name "*.txt" -o -name "*.sh" \) -print`
    - chmod 755 `find . -type f -name "*.sh" -print`

compile_microbench:
    stage: build
    script:
        - cd microbench
        - ./compile.sh
    artifacts:
        paths:
            - microbench/bin

test_microbench_istree_throughput:
    stage: test
    script:
        - mkdir -p tests
        - maxthr=`cd microbench/experiments ; ./get_thread_count_max.sh`
        - thread_pinning=`cd microbench/experiments ; ./get_pinning_cluster.sh`
        - args="-nwork ${maxthr} -nprefill ${maxthr} -i 5 -d 5 -rq 0 -rqsize 1 -k 2000000 -nrq 0 -t 10000 -pin ${thread_pinning}"
        - f="tests/test_microbench_istree_throughput.txt"
        - echo maxthr="$maxthr" thread_pinning="$thread_pinning" f="$f" args="$args"
        - pwd
        - LD_PRELOAD=./lib/libjemalloc.so timeout 600 numactl --interleave=all time ./microbench/bin/ubench_brown_ext_ist_lf.alloc_new.reclaim_debra.pool_none.out $args | tee $f 2>&1
        - tput=`cat $f | grep "total through" | cut -d":" -f2 | tr -d " "`
        - echo "tput=$tput"

# dependencies
# dos2unix          sudo apt install dos2unix
# numactl           sudo apt install numactl
# libnuma           sudo apt install libnuma-dev
# papi              
# timeout, time

### next up: figure out how to parse things.... or just offload this kind of results validation to .sh files???
### add tests folder to artifacts and pass to a validation stage? or leave as part of tests?
